// {
//   id: ,
//   name: ,
//   category: ,
//   imageUrl: ,
//   description: ,
//   article: ,
//   model: ,
// },

const products = [
  {
    id: 'A5100',
    name: 'Продукт 1',
    category: '1Progress',
    imageUrl: '../assets/roliki-42-37-0.jpg',
    description: 'Описание продукта 1',
    article: 'A5100',
    model: 'LADA, Renault',
  },
  {
    id: 'A5102',
    name: 'НАСОС2 ТОПЛИВНЫЙ ЭЛЕКТРИЧЕСКИЙ ГАЗ 3110, 3302 (0 580 454 001, 110Л/Ч)',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Описание продукта 2',
    article: 'A5102',
    model: 'LADA, Renault',
  },
  {
    id: 'A5101',
    name: 'Фильтр воздушный ГАЗель Next',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высококачественный фильтр для ГАЗель Next.',
    article: 'XZ102',
    model: 'ГАЗель Next',
  },
  {
    id: 'A5103',
    name: 'Подшипник ступицы ВАЗ 2110',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Надежный подшипник ступицы для ВАЗ 2110.',
    article: 'XZ103',
    model: 'ВАЗ 2110',
  },
  {
    id: 'B5201',
    name: 'Аккумуляторная батарея Bosch',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Долговечная аккумуляторная батарея Bosch для всех типов автомобилей.',
    article: 'BX200',
    model: 'Универсальная',
  },
  {
    id: 'B5202',
    name: 'Тормозные колодки Brembo для Ford Focus',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высокоэффективные тормозные колодки от Brembo.',
    article: 'BX201',
    model: 'Ford Focus',
  },
  {
    id: 'A5gd',
    name: 'Фильтр воздушный ГАЗель Next',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высококачественный фильтр для ГАЗель Next.',
    article: 'FVGN1',
    model: 'ГАЗель Next',
  },
  {
    id: 'A5523',
    name: 'Подшипник ступицы ВАЗ 2110',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Надежный подшипник ступицы для ВАЗ 2110.',
    article: 'PSV2110',
    model: 'ВАЗ 2110',
  },
  {
    id: 'B525253',
    name: 'Аккумуляторная батарея Bosch',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Долговечная аккумуляторная батарея Bosch для всех типов автомобилей.',
    article: 'ABBB1',
    model: 'Универсальная',
  },
  {
    id: 'B52322',
    name: 'Тормозные колодки Brembo для Ford Focus',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высокоэффективные тормозные колодки от Brembo.',
    article: 'TBFF1',
    model: 'Ford Focus',
  },
  {
    id: 'A5100',
    name: 'Продукт 1',
    category: '1Progress',
    imageUrl: '../assets/roliki-42-37-0.jpg',
    description: 'Описание продукта 1',
    article: 'A5100',
    model: 'LADA, Renault',
  },
  {
    id: 'A5102',
    name: 'НАСОС2 ТОПЛИВНЫЙ ЭЛЕКТРИЧЕСКИЙ ГАЗ 3110, 3302 (0 580 454 001, 110Л/Ч)',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Описание продукта 2',
    article: 'A5102',
    model: 'LADA, Renault',
  },
  {
    id: 'A5101',
    name: 'Фильтр воздушный ГАЗель Next',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высококачественный фильтр для ГАЗель Next.',
    article: 'XZ102',
    model: 'ГАЗель Next',
  },
  {
    id: 'A5103',
    name: 'Подшипник ступицы ВАЗ 2110',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Надежный подшипник ступицы для ВАЗ 2110.',
    article: 'XZ103',
    model: 'ВАЗ 2110',
  },
  {
    id: 'B5201',
    name: 'Аккумуляторная батарея Bosch',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Долговечная аккумуляторная батарея Bosch для всех типов автомобилей.',
    article: 'BX200',
    model: 'Универсальная',
  },
  {
    id: 'B5202',
    name: 'Тормозные колодки Brembo для Ford Focus',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высокоэффективные тормозные колодки от Brembo.',
    article: 'BX201',
    model: 'Ford Focus',
  },
  {
    id: 'A5gd',
    name: 'Фильтр воздушный ГАЗель Next',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высококачественный фильтр для ГАЗель Next.',
    article: 'FVGN1',
    model: 'ГАЗель Next',
  },
  {
    id: 'A5523',
    name: 'Подшипник ступицы ВАЗ 2110',
    category: '1Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Надежный подшипник ступицы для ВАЗ 2110.',
    article: 'PSV2110',
    model: 'ВАЗ 2110',
  },
  {
    id: 'B525253',
    name: 'Аккумуляторная батарея Bosch',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Долговечная аккумуляторная батарея Bosch для всех типов автомобилей.',
    article: 'ABBB1',
    model: 'Универсальная',
  },
  {
    id: 'B52322',
    name: 'Тормозные колодки Brembo для Ford Focus',
    category: '2Progress',
    imageUrl: '../assets/nasos.jpg',
    description: 'Высокоэффективные тормозные колодки от Brembo.',

    article: 'TBFF1',
    model: 'Ford Focus',
  },
];

export default products;
